on: [push, pull_request]

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
        - name: Verify Git repository
          uses: actions/checkout@v2

        - name: Install node
          uses: actions/setup-node@v1
          with:
            node-version: 16


        - name: install dependencies
          run: npm install

        - name: executes eslint
          run: npx eslint .